spring.application.name=api_sincdb
server.servlet.context-path=/sincdb
spring.mvc.static-path-pattern=/static/**


#pool de conexao
spring.datasource.hikari.connection-timeout= 20000
spring.datasource.hikari.minimum-idle= 10
spring.datasource.hikari.auto-commit=true
spring.main.allow-bean-definition-overriding=true
spring.datasource.hikari.max-lifetime=60000
spring.datasource.hikari.idle-timeout= 300000

spring.profiles.active=mongo

springdoc.swagger-ui.use-root-path=true
server.forward-headers-strategy=framework
springdoc.swagger-ui.path=/swagger-ui.html


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.datasource.hikari.maximum-pool-size=10

